[package]
name = "cuer_manager"
version = "0.3.0"
authors = ["Alexander Sopicki"]
build = "build.rs"

[dependencies]

rocket = "0.2.9"
rocket_codegen = "0.2.9"
rs-es = "0.10.0"
json_str = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
unescape = "0.1.0"
comrak = "0.1.4"


[dev-dependencies]
rocket = { version = "0.2.9", features = ["testing"] }
