[package]
name = "cuer_manager"
version = "0.4.0"
authors = ["Alexander Sopicki"]

[dependencies]

rocket = "0.3.0"
rocket_codegen = "0.3.0"
rs-es = "0.10.0"
json_str = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
hyper = "^0.10.11"
unescape = "0.1.0"
comrak = "0.1.4"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

